name: Bug Report
description: Report a bug or incorrect behavior
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Minimal steps to trigger the bug.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `sp-local-bridge --version`
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Linux amd64
        - Linux arm64
        - macOS amd64
        - macOS arm64
        - Windows amd64
        - Windows arm64
    validations:
      required: true
